#!/bin/sh

CURL_CONFIG="/usr/bin/$(dpkg-architecture -qDEB_HOST_GNU_TYPE)-curl-config"

if [ -x "$CURL_CONFIG" ]; then
	exec "$CURL_CONFIG" "$@"
else
	echo "$CURL_CONFIG not found, try installing the package for $(dpkg-architecture -qDEB_HOST_ARCH) architecture" >&2
	exit 1
fi
